#
# SPECPR main makefile
#
SHELL=/bin/sh

# to add a new directory, add to DIRS and OBJ.  That's all!

DIRS= \
common 3dio add band crtp dtol dummy dvml extn fass \
fcn01-08 fcn09-11 fcn12-13 fcn14-16 fcn17-19 \
fcn20-25 fcn35-39 fcn40-42 fcn43-47 fcn48-51 \
free gould hed hpgraph init interbandanl io lib main \
mth1 mth2 newplot parser rst sub syslib $(SPSDIR) talg wav xwindow

OBJ= \
$(SP_OBJ)/3dio.o $(SP_OBJ)/add.o $(SP_OBJ)/band.o $(SP_OBJ)/crtp.o \
$(SP_OBJ)/dtol.o $(SP_OBJ)/dummy.o $(SP_OBJ)/dvml.o $(SP_OBJ)/extn.o \
$(SP_OBJ)/fass.o $(SP_OBJ)/fcn01-08.o $(SP_OBJ)/fcn09-11.o \
$(SP_OBJ)/fcn12-13.o $(SP_OBJ)/fcn14-16.o $(SP_OBJ)/fcn17-19.o \
$(SP_OBJ)/fcn20-25.o $(SP_OBJ)/fcn35-39.o $(SP_OBJ)/fcn40-42.o \
$(SP_OBJ)/fcn43-47.o $(SP_OBJ)/fcn48-51.o $(SP_OBJ)/free.o \
$(SP_OBJ)/gould.o $(SP_OBJ)/hed.o $(SP_OBJ)/hpgraph.o $(SP_OBJ)/init.o \
$(SP_OBJ)/interbandanl.o $(SP_OBJ)/io.o $(SP_OBJ)/lib.o $(SP_OBJ)/main.o \
$(SP_OBJ)/mth1.o $(SP_OBJ)/mth2.o $(SP_OBJ)/newplot.o \
$(SP_OBJ)/parser.o $(SP_OBJ)/rst.o $(SP_OBJ)/sub.o \
$(SP_OBJ)/syslib.o $(SPSYSOBJ) $(SP_OBJ)/talg.o \
$(SP_OBJ)/wav.o $(SP_OBJ)/xwindow.o

# make all does a compile from scratch: it goes into all
#      subdirectories and does a make on each.
#
all:	$(SP_OBJ)/common.o all_dirs $(SP_LIB)/specpr.a
	$(F77) $(FFLAGS) $(LDFLAGS) -o xdspecpr main/specpr.o \
		$(SP_OBJ)/common.o \
		$(SP_LIB)/specpr.a $(LDLIBS)
	mv dspecpr dspecpr.old1
	mv xdspecpr dspecpr
#	rm dspecpr.old1


$(SP_OBJ)/common.o:
	-@(cd common ; get -s SCCS/s.makefile 2> /dev/null ; chmod 666 makefile)
	@(cd common ; echo "making in common" ; make)

all_dirs:	$(SP_OBJ)/common.o $(OBJ)

#
# this one checks all $(SP_OBJ)ects
#
specpr.a:	$(SP_OBJ)/common.o $(OBJ)
	rm -f $(SP_LIB)/specpr.a
	$(AR) $(ARFLAGS) $(SP_LIB)/specpr.a $(SP_OBJ)/common.o $(OBJ)
	$(RANLIB) $(SP_LIB)/specpr.a

$(SP_LIB)/specpr.a:	$(SP_OBJ)/common.o $(OBJ)
	rm -f $(SP_LIB)/specpr.a
	$(AR) $(ARFLAGS) $(SP_LIB)/specpr.a $(SP_OBJ)/common.o $(OBJ)
	$(RANLIB) $(SP_LIB)/specpr.a

$(DIRS)::
	-@(cd $(@F:.o=) ; sp_if_get SCCS/s.makefile makefile 2> /dev/null)
	@(cd $@ ; echo "making all in $@" ; make)
	@echo "*** specpr.a may need to be remade.. If so, type 'make specpr.a'"

$(OBJ)::	
	-@(cd $(@F:.o=) ; sp_if_get SCCS/s.makefile makefile 2> /dev/null)
	@(cd $(@F:.o=) ; echo "making all in $(@F:.o=)" ; make)

# removes big .o files, temp and debug and specpr.a
#         it does not remove .o in each sub directory.
clean:
	-rm -f $(SP_OBJ)/* ../tmp/* ../debug/* $(SP_LIB)/specpr.a

# this removes what clean does plus all .o's in sub dirs, and all .h
#      and makefiles.  WARNING: do not do this if you have SCCS files
#      checked out.

really_clean:
	-rm -f $(SP_OBJ)/* ../tmp/* ../debug/* $(SP_LIB)/specpr.a
	for i in $(DIRS) ;\
	do \
		(cd $$i ; echo "cleaning all in $$i" ; rm -f *.o) ;\
	done

temp:	
	$(F77) $(FFLAGS) $(LDFLAGS) -o xdspecpr main/specpr.o $(SP_OBJ)/common.o \
	$(OBJ) $(LDLIBS)
	mv xdspecpr dspecpr

dspecpr:
		$(F77) $(FFLAGS) $(LDFLAGS) -o xdspecpr main/specpr.o \
		$(SP_OBJ)/common.o \
		$(SP_LIB)/specpr.a $(LDLIBS)
		mv xdspecpr dspecpr

install:	dspecpr
	cp -p dspecpr $(SP_LOCAL)/bin/pspecpr
	chmod 755 $(SP_LOCAL)/bin/pspecpr
	cp -p dspecpr.sh $(SP_LOCAL)/bin/dspecpr
	chmod 755 $(SP_LOCAL)/bin/dspecpr
	cp -p specpr.sh $(SP_LOCAL)/bin/specpr
	chmod 755 $(SP_LOCAL)/bin/specpr
