GET= get
SPRDIR=../specpr/

OBJ = tetracorder.o	\
makvicarlabel.o		\
readi2sheet.o		\
setupreadsheet.o	\
rstbgn.o		\
strdate.o		\
delhist.o		\
tri1setup.o		\
reflsetup.o		\
cubecorder.o		\
specorder.o		\
tp1mat.o		\
tp1all.o		\
flushseqfile.o		\
opencube.o		\
wrtspcrdrout.o		\
wrtcrdrout.o		\
gcsetup.o		\
wrtgcsetup.o		\
creatoutfiles.o		\
cublineout.o		\
tp1cse.o		\
nvres1mat.o		\
i4pack4.o		\
../specpr/src.specpr/common/blockdata.o

INCL= \
../specpr/src.specpr/common/label1 \
../specpr/src.specpr/common/lbl3 \
../specpr/src.specpr/common/lbl4 \
../specpr/src.specpr/common/lbl7 \
../specpr/src.specpr/common/lundefs \
../specpr/src.specpr/common/alphabet \
../specpr/src.specpr/common/cmd \
../specpr/src.specpr/common/lblg \
../specpr/src.specpr/common/lblwav \
../specpr/src.specpr/common/cmdarg \
../specpr/src.specpr/common/dscrch \
../specpr/src.specpr/common/ioftyp \
../specpr/src.specpr/common/blank \
../specpr/src.specpr/common/lblvol \
tri1.h	\
obuffers.h	\
multmap.h

tetracorder:	$(OBJ) $(SPRDIR)/lib/specpr.a ../cubeio/cubeio.a
	$(F77) $(FFLAGS) $(LDFLAGS) -o tetracorder $(OBJ) \
			$(SPRDIR)/lib/specpr.a	\
			../cubeio/cubeio.a $(LDLIBS)

install:
	mv tetracorder /usr/local/bin/tetracorder4.0
	chmod 755 /usr/local/bin/tetracorder4.0
	size /usr/local/bin/tetracorder4.0

.SUFFIXES:
.SUFFIXES: .o .r .f


tetracorder.o:	tetracorder.r $(INCL) tricube.h tri1.h multmap.h obuffers.h
		$(SSPP) -r -$(SSPPFLAGS) tetracorder.r > tetracorder.x
		$(RF) $(RFLAGS) tetracorder.x > tetracorder.f
		rm tetracorder.x
		$(F77) $(FFLAGS) -c tetracorder.f
		rm tetracorder.f

makvicarlabel.o:	makvicarlabel.r
		$(RF) $(RFLAGS) makvicarlabel.r > makvicarlabel.f
		$(F77) $(FFLAGS) -c makvicarlabel.f
		rm makvicarlabel.f

readi2sheet.o:	readi2sheet.r
		$(RF) $(RFLAGS) readi2sheet.r > readi2sheet.f
		$(F77) $(FFLAGS) -c readi2sheet.f
		rm readi2sheet.f

setupreadsheet.o:	setupreadsheet.r
		$(RF) $(RFLAGS) setupreadsheet.r > setupreadsheet.f
		$(F77) $(FFLAGS) -c setupreadsheet.f
		rm setupreadsheet.f

strdate.o:	strdate.r
		$(RF) $(RFLAGS) strdate.r > strdate.f
		$(F77) $(FFLAGS) -c strdate.f
		rm strdate.f

rstbgn.o:	rstbgn.r
		$(SSPP) -r -$(SSPPFLAGS) ../specpr/src.specpr/common/filenames.hs > ../specpr/src.specpr/common/filenames 
		$(SSPP) -r -$(SSPPFLAGS) rstbgn.r > rstbgn.x
		$(RF) $(RFLAGS) rstbgn.x > rstbgn.f
		$(F77) $(FFLAGS)  -c rstbgn.f
		rm rstbgn.f rstbgn.x ../specpr/src.specpr/common/filenames

i4pack4.o:	i4pack4.c
		$(SSPP) -c -$(SSPPFLAGS) i4pack4.c > tmpi4pack4.c
		cc $(CFLAGS) -c -o i4pack4.o tmpi4pack4.c
		rm tmpi4pack4.c

delhist.o:	delhist.r
		$(RF) $(RFLAGS) delhist.r > delhist.f
		$(F77) $(FFLAGS) -c delhist.f
		rm delhist.f

tri1setup.o:	tri1setup.r tri1.h multmap.h
		$(RF) $(RFLAGS) tri1setup.r > tri1setup.f
		$(F77) $(FFLAGS) -c tri1setup.f
		rm tri1setup.f

reflsetup.o:	reflsetup.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) reflsetup.r > reflsetup.f
		$(F77) $(FFLAGS) -c reflsetup.f
		rm reflsetup.f

cubecorder.o:	cubecorder.r tricube.h tri1.h multmap.h obuffers.h
		$(RF) $(RFLAGS) cubecorder.r > cubecorder.f
		$(F77) $(FFLAGS) -c cubecorder.f
		rm cubecorder.f

specorder.o:	specorder.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) specorder.r > specorder.f
		$(F77) $(FFLAGS) -c specorder.f
		rm specorder.f

tp1mat.o:	tp1mat.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) tp1mat.r > tp1mat.f
		$(F77) $(FFLAGS2) $(FOPT2) -c tp1mat.f
		rm tp1mat.f

tp1all.o:	tp1all.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) tp1all.r > tp1all.f
		$(F77) $(FFLAGS2) $(FOPT2) -c tp1all.f
		rm tp1all.f

flushseqfile.o:	flushseqfile.r
		$(RF) $(RFLAGS) flushseqfile.r > flushseqfile.f
		$(F77) $(FFLAGS) -c flushseqfile.f
		rm flushseqfile.f

opencube.o:	opencube.r
		$(RF) $(RFLAGS) opencube.r > opencube.f
		$(F77) $(FFLAGS) -c opencube.f
		rm opencube.f

wrtspcrdrout.o:	wrtspcrdrout.r multmap.h
		$(RF) $(RFLAGS) wrtspcrdrout.r > wrtspcrdrout.f
		$(F77) $(FFLAGS) -c wrtspcrdrout.f
		rm wrtspcrdrout.f

wrtcrdrout.o:	wrtcrdrout.r multmap.h
		$(RF) $(RFLAGS) wrtcrdrout.r > wrtcrdrout.f
		$(F77) $(FFLAGS) -c wrtcrdrout.f
		rm wrtcrdrout.f

gcsetup.o:	gcsetup.r multmap.h
		$(RF) $(RFLAGS) gcsetup.r > gcsetup.f
		$(F77) $(FFLAGS) -c gcsetup.f
		rm gcsetup.f

wrtgcsetup.o:	wrtgcsetup.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) wrtgcsetup.r > wrtgcsetup.f
		$(F77) $(FFLAGS) -c wrtgcsetup.f
		rm wrtgcsetup.f

creatoutfiles.o:	creatoutfiles.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) creatoutfiles.r > creatoutfiles.f
		$(F77) $(FFLAGS) -c creatoutfiles.f
		rm creatoutfiles.f

cublineout.o:	cublineout.r tricube.h tri1.h multmap.h obuffers.h
		$(RF) $(RFLAGS) cublineout.r > cublineout.f
		$(F77) $(FFLAGS) -c cublineout.f
		rm cublineout.f

nvres1mat.o:	nvres1mat.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS) nvres1mat.r > nvres1mat.f
		$(F77) $(FFLAGS) -c nvres1mat.f
		rm nvres1mat.f

tp1cse.o:	tp1cse.r tricube.h tri1.h multmap.h
		$(RF) $(RFLAGS)  tp1cse.r > tp1cse.f
		$(F77) $(FFLAGS2) $(FOPT2) -c tp1cse.f
		rm tp1cse.f

